


redis:
  host: person101
  password: 123
  key: pattern
spring:
  redis:
    host: person101
    port: 6379
    password: root
    database: 0
    lettuce:
      pool:
        max-active: 8 # 最大连接数
        max-idle: 8    # 最大空闲连接
        min-idle: 0    # 最小空闲连接
        max-wait: 100    # 最大等待时长
